# async 函数

- 返回值为 Promise
- 可以使用 then 添加回调

```js
function timeout(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms)
  })
)

async function asyncPrint(value, ms) {
  await timeout(ms)
  console.log(value)
}

asyncPrint('hello world', 50)
```

---

## await 命令

- 后面是一个 Promise 对象。如果不是，会被转成一个立即resolve的 Promise 对象
- await 后的 Promise 变更为 reject 后，中断函数执行进入 catch 逻辑

```js
async function f() {
  await Promise.reject('出错了');
  await Promise.resolve('hello world'); // 不会执行
}
```

```js
async function f() {
  try {
    await Promise.reject('出错了')
  } catch(e) {
  }
  return await Promise.resolve('hello world')
}

f()
.then(v => console.log(v))
// hello world
```

---

## 串行与并行

并行

```js
// 写法一
let [foo, bar] = await Promise.all([getFoo(), getBar()]);

// 写法二
let fooPromise = getFoo();
let barPromise = getBar();
let foo = await fooPromise;
let bar = await barPromise;
```

forEach

```js
function dbFuc(db) { //这里不需要 async
  let docs = [{}, {}, {}];

  // 可能得到错误结果
  docs.forEach(async function (doc) {
    await db.post(doc);
  });
}
```

for of

```js
async function dbFuc(db) {
  let docs = [{}, {}, {}];

  for (let doc of docs) {
    await db.post(doc);
  }
}
```
